"""add embeddings to code chunks

Revision ID: 74a54b915235
Revises: dc4d983fe7e4
Create Date: 2026-08-20 20:15:47.884575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a54b915235'
down_revision: Union[str, None] = 'dc4d983fe7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_chunks', 'embedding')
    # ### end Alembic commands ###
